# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

minReadySeconds: 5
preStopSleepSeconds: 5
networkTester:
  image:
    repository: cr.yandex/crp1of6bddata8ain3q5/k8s-network-tester
    tag: latest

app:
  image:
    repository: cr.yandex/crp1of6bddata8ain3q5/storage

  resources:
    requests:
      cpu: 0.01
      memory: 50Mi
    limits:
      memory: 100Mi

env:
  RUST_LOG: info
  CACHE_ENABLED: 0
  CACHE_POOL_SIZE: 50
  CACHE_POOL_IDLE_SIZE: 5
  CACHE_POOL_TIMEOUT: 5
  CACHE_EXPIRATION_TIME: 600

clusterService:
  ports:
    http: 8080

tls:
  secretName: tls-certificates
