language: rust
rust:
  - stable
addons:
  apt:
    packages:
      - awscli
cache:
  directories:
    - ${TRAVIS_HOME}/.cargo
before_cache:
  - rm -rf ${TRAVIS_HOME}/.cargo/registry
services: docker
git:
  depth: 1
jobs:
  include:
    - stage: check
      name: Tests
      script: cargo test
    - stage: check
      name : Rustfmt
      install: rustup component add rustfmt-preview
      script: cargo fmt -- --check
    - stage: check
      name: Clippy
      install: rustup component add clippy-preview
      script: cargo clippy
    - stage: check
      name: Docs
      install: cargo install mdbook --vers 0.2.3 --force
      script: mdbook build docs && ./deploy.init.sh && PROJECT='storage' ./deploy/s3-docs.sh
    - stage: deploy
      name: Kubernetes
      script: ./deploy.init.sh && ./deploy/travis-run.sh
stages:
  - name: check
  - name: deploy
    if: (branch = master AND type = push) OR tag IS present
notifications:
  email: false
