[package]
name = "storage"
version = "0.1.0"
authors = ["Andrei Nesterov <ae.nesterov@gmail.com>"]

[dependencies]
log = "0.4.0"
env_logger = "0.5.12"
config = "0.9"
serde = "1.0.75"
rusoto_core = { git = "https://github.com/rusoto/rusoto.git", rev = "52b288a7edd1bd3799fb1bb67841a7b2d8ed18f8" }
rusoto_s3 = { git = "https://github.com/rusoto/rusoto.git", rev = "52b288a7edd1bd3799fb1bb67841a7b2d8ed18f8" }
tower-web = "0.2.1"
http = "0.1.10"