[package]
name = "storage"
version = "0.2.3"
authors = ["Andrei Nesterov <ae.nesterov@gmail.com>"]

[dependencies]
log = "0.4.6"
env_logger = "0.6.0"
config = "0.9.1"
failure = "0.1.3"
serde = "1.0.80"
jsonwebtoken = "5.0.1"
rusoto_core = "0.35.0"
rusoto_s3 = "0.35.0"
tower-web = "0.3.2"
reqwest = "0.9.5"
http = "0.1.14"
