[package]
name = "storage"
version = "0.3.2"
authors = ["Andrei Nesterov <ae.nesterov@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
env_logger = "0.6"
config = "0.9"
failure = "0.1"
serde = "1.0"
serde_derive = "1.0"
futures = "0.1"
radix_trie = "0.1"
rusoto_core = "0.40"
rusoto_s3 = "0.40"
tower-web = "0.3"
http = "0.1"
svc-authn = { version = "0.5", features = ["jose", "tower-web"] }
svc-authz = "0.6"
