[package]
name = "storage"
version = "0.2.2"
authors = ["Andrei Nesterov <ae.nesterov@gmail.com>"]

[dependencies]
log = "0.4.0"
env_logger = "0.5.12"
config = "0.9"
failure = "0.1.2"
serde = "1.0.75"
jsonwebtoken = "5.0.1"
rusoto_core = "0.34.0"
rusoto_s3 = "0.34.0"
tower-web = "0.2.2"
reqwest = "0.9.1"
http = "0.1.10"
