[package]
name = "storage"
version = "0.6.1"
authors = ["Andrei Nesterov <ae.nesterov@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
log = "0.4"
env_logger = "0.6"
config = "0.9"
serde = "1.0"
serde_derive = "1.0"
futures = "0.1"
radix_trie = "0.1"
rusoto_core = "0.40"
rusoto_s3 = "0.40"
uuid = { version = "0.6", features = ["v4"] }
chrono = "0.4"
openssl = "*"
diesel = { version = "1.4", features = ["postgres", "uuid", "chrono", "r2d2"] }
tower-web = "0.3"
http = "0.2"
url = "1.7"
svc-authn = { version = "0.5", features = ["jose", "tower-web"] }
svc-authz = "0.7"
