[package]
name = "storage"
version = "0.3.0"
authors = ["Andrei Nesterov <ae.nesterov@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
env_logger = "0.6"
config = "0.9"
failure = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
jsonwebtoken = { git = "https://github.com/manifest/jsonwebtoken", branch = "feature/ec" }
chrono = { version = "0.4" }
rusoto_core = "0.35"
rusoto_s3 = "0.35"
tower-web = "0.3"
reqwest = "0.9"
http = "0.1"
