apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
    - image: netologygroup/storage
      docker:
        dockerfile: docker/Dockerfile
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:{{.IMAGE_TAG}}'
  local:
    push: true
    useDockerCLI: true
deploy:
  kubectl:
    manifests:
      - deploy/k8s/storage-v2.yaml
      - deploy/k8s/storage-v2-config.yaml
      - deploy/k8s/storage-v2-environment.yaml
      - deploy/k8s/storage-v2-ingress.yaml
      - deploy/k8s/storage-v2-service.yaml
