apiVersion: skaffold/v2beta4
kind: Config
build:
  artifacts:
  - image: netologygroup/storage
    docker:
      dockerfile: docker/Dockerfile
  tagPolicy:
    gitCommit: {}
  local:
    push: true
    useDockerCLI: true
deploy:
  helm:
    releases:
    - name: storage-v1
      chartPath: chart
      artifactOverrides:
        container.image: foxford/storage:XXXXX # TODO: set specific image tag
      imageStrategy:
        helm: {}
      valuesFiles:
