apiVersion: skaffold/v2beta11
kind: Config
build:
  artifacts:
  - image: foxford/storage
    docker:
      dockerfile: docker/Dockerfile
  tagPolicy:
    gitCommit: {}
  local:
    push: true
    useDockerCLI: true
    tryImportMissing: true
deploy:
  helm:
    releases:
      - name: "{{ .PROJECT }}"
        chartPath: chart
        artifactOverrides:
          app.image: foxford/storage
        imageStrategy:
          helm: {}
        valuesFiles:
          - deploy/values.yaml
