apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "storage.fullname" . }}
  labels:
    {{- include "storage.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "storage.selectorLabels" . | nindent 6 }}
