{{- if and .Values.maxmind (ge (keys .Values.app.s3 | len) 1) }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "storage.fullname" . }}-restarter
  labels:
    {{- include "storage.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.maxmind.updateSchedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ include "storage.fullname" . }}-restarter
          restartPolicy: OnFailure
          containers:
            - name: kubectl
              image: bitnami/kubectl
              command:
                - /bin/sh
                - -c
                - "kubectl rollout restart deployment/{{ include "storage.fullname" . }}"
{{- end }}
