apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage
  labels:
    app: storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage
  template:
    metadata:
      labels:
        app: storage
    spec:
      containers:
        - name: storage
          image: netologygroup/storage
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: "AWS_ACCESS_KEY_ID"
              valueFrom:
                secretKeyRef:
                  name: aws-s3-credentials
                  key: key
            - name: "AWS_SECRET_ACCESS_KEY"
              valueFrom:
                secretKeyRef:
                  name: aws-s3-credentials
                  key: secret
            - name: "AWS_ENDPOINT"
              valueFrom:
                secretKeyRef:
                  name: aws-s3-credentials
                  key: endpoint
            - name: "AWS_REGION"
              valueFrom:
                secretKeyRef:
                  name: aws-s3-credentials
                  key: region
            - name: "RUST_LOG"
              valueFrom:
                configMapKeyRef:
                  name: storage-environment
                  key: RUST_LOG
          volumeMounts:
            - name: config
              mountPath: /app/App.toml
              subPath: App.toml
            - name: iam
              mountPath: /app/data/keys/iam.public_key.p8.der
              subPath: iam.public_key
            - name: svc
              mountPath: /app/data/keys/svc.private_key.p8.der
              subPath: svc.private_key
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 500m
              memory: 1Gi
      volumes:
        - name: config
          configMap:
            name: storage-config
        - name: iam
          secret:
            secretName: iam-pkcs8-der-credentials
        - name: svc
          secret:
            secretName: svc-pkcs8-der-credentials
