apiVersion: v1
kind: Service
metadata:
  name: {{ include "storage.clusterServiceName" . }}
  labels:
    {{- include "storage.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: {{ .Values.clusterService.ports.http }}
      targetPort: 8080
      protocol: TCP
  selector:
    {{- include "storage.selectorLabels" . | nindent 4 }}
