apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "storage.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  labels:
    {{- include "storage.labels" . | nindent 4 }}
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ .Values.ingress.tls.secretName }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ include "storage.ingressPath" . }}(/|$)(.*)
            pathType: Prefix
            backend:
              serviceName: {{ include "storage.clusterServiceName" $ }}
              servicePort: {{ .Values.clusterService.ports.http }}
