{{- if .Values.legacyIngress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "storage.fullname" . }}-legacy
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    {{- include "storage.labels" . | nindent 4 }}
spec:
  tls:
    - hosts:
        - {{ .Values.legacyIngress.host | quote }}
      secretName: {{ .Values.tls.secretName }}
  rules:
    - host: {{ .Values.legacyIngress.host | quote }}
      http:
        paths:
          - path: /
            backend:
              service:
                name: {{ include "storage.fullname" . }}-cluster
                port:
                  number: {{ .Values.clusterService.ports.http }}
{{- end }}
