{{- if .Values.legacyIngress }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "storage.fullname" . }}-legacy
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    {{- include "storage.labels" . | nindent 4 }}
spec:
  tls:
    - hosts:
        - {{ .Values.legacyIngress.host | quote }}
      secretName: {{ .Values.tls.secretName }}
  rules:
    - host: {{ .Values.legacyIngress.host | quote }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ include "storage.fullname" . }}-cluster
              servicePort: {{ .Values.clusterService.ports.http }}
{{- end }}
