{{- if .Values.legacyIngress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "storage.fullname" . }}-legacy
  labels:
    {{- include "storage.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.legacyIngress.class | quote }}
  tls:
    - hosts:
        {{- range $host := .Values.legacyIngress.hosts }}
        - {{ $host | quote }}
        {{- end }}
      secretName: {{ .Values.tls.secretName }}
  rules:
    {{- range $host := .Values.legacyIngress.hosts }}
    - host: {{ $host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "storage.fullname" $ }}-cluster
                port:
                  number: {{ $.Values.clusterService.ports.http }}
    {{- end }}
{{- end }}
